In [2]:
import numpy as np
import pandas as pd
import time
import datetime

In [3]:
data = pd.read_csv('rp5.ru/погода.csv')
table0 = data[['Местное время в Шереметьево / им. А. С. Пушкина (аэропорт)', 'T', 'W1', 'N']]
table0['hour'] = [time.strptime(n, "%d.%m.%Y %H:%M").tm_hour for n in table0['Местное время в Шереметьево / им. А. С. Пушкина (аэропорт)']]
table0['day'] = [time.strptime(n, "%d.%m.%Y %H:%M").tm_mday for n in table0['Местное время в Шереметьево / им. А. С. Пушкина (аэропорт)']]
table0['month'] = [time.strptime(n, "%d.%m.%Y %H:%M").tm_mon for n in table0['Местное время в Шереметьево / им. А. С. Пушкина (аэропорт)']]
table0['year'] = [time.strptime(n, "%d.%m.%Y %H:%M").tm_year for n in table0['Местное время в Шереметьево / им. А. С. Пушкина (аэропорт)']]
table0['status'] = [1 if n >= 12 else 0 for n in table0['hour']]
table0.drop(['Местное время в Шереметьево / им. А. С. Пушкина (аэропорт)'], axis='columns', inplace=True)
table0 = table0.sort_values(by=['year', 'month', 'day', 'hour'])
table0.loc[(table0['N'] == 'Облаков нет.') & (table0['W1'].isnull()), 'W1'] = 'Облаков нет.'
table0['W1'] = [np.nan if n == ' ' else n for n in table0['W1']]
table0 = table0.dropna()

/home/dmitry/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/dmitry/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/home/dmitry/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[r

In [4]:
table1 = table0.loc[(table0['month'] == 1)]
table2 = table0.loc[(table0['month'] == 2)]
table3 = table0.loc[(table0['month'] == 3)]
table4 = table0.loc[(table0['month'] == 4)]
table5 = table0.loc[(table0['month'] == 5)]
table6 = table0.loc[(table0['month'] == 6)]
table7 = table0.loc[(table0['month'] == 7)]
table8 = table0.loc[(table0['month'] == 8)]
table9 = table0.loc[(table0['month'] == 9)]
table10 = table0.loc[(table0['month'] == 10)]
table11 = table0.loc[(table0['month'] == 11)]
table12 = table0.loc[(table0['month'] == 12)]
table_np1 = table1.values
table_np2 = table2.values
table_np3 = table3.values
table_np4 = table4.values
table_np5 = table5.values
table_np6 = table6.values
table_np7 = table7.values
table_np8 = table8.values
table_np9 = table9.values
table_np10 = table10.values
table_np11 = table11.values
table_np12 = table12.values

In [5]:
table6

T                                                 W1  \
24574  16.9                                    Ливень (ливни).   
24573  16.7                                    Ливень (ливни).   
24572  18.4                                    Ливень (ливни).   
24571  20.4                                    Ливень (ливни).   
24570  17.1                                    Ливень (ливни).   
24569  16.3  Облака покрывали более половины неба в течение...   
24568  14.9  Облака покрывали более половины неба в течение...   
24567  16.3  Облака покрывали более половины неба в течение...   
24566  19.0  Облака покрывали более половины неба в течение...   
24563  22.8                                    Ливень (ливни).   
24562  19.4                                    Ливень (ливни).   
24560  14.7  Облака покрывали половину неба или менее в теч...   
24554  23.5              Гроза (грозы) с осадками или без них.   
24553  18.7              Гроза (грозы) с осадками или без них.   
24552  17.6              Гроза (грозы) с осадками или без них.   
24548  17.2              Гроза (грозы) с осадками или без них.   
24547  20.6              Гроза (грозы) с осадками или без них.   
24546  16.2              Гроза (грозы) с осадками или без них.   
24545  15.1                                    Ливень (ливни).   
24544  12.9                                    Ливень (ливни).   
24543  12.4                                             Дождь.   
24542  13.2                                             Дождь.   
24538  12.3                                             Дождь.   
24537   8.0                                             Дождь.   
24536   8.0                                             Дождь.   
24528  12.3                                    Ливень (ливни).   
24527  12.1                                    Ливень (ливни).   
24526  13.5                                    Ливень (ливни).   
24525  16.2                                    Ливень (ливни).   
24524  17.8                                    Ливень (ливни).   
...     ...                                                ...   
2429   14.3                                    Ливень (ливни).   
2428   13.8                                    Ливень (ливни).   
2427   12.4                                    Ливень (ливни).   
2426   13.0          Туман или ледяной туман или сильная мгла.   
2425   14.5          Туман или ледяной туман или сильная мгла.   
2424   13.5                                    Ливень (ливни).   
2423   13.4                                    Ливень (ливни).   
2422   13.1                                    Ливень (ливни).   
2421   13.9                                    Ливень (ливни).   
2420   14.1                                    Ливень (ливни).   
2419   13.8                                    Ливень (ливни).   
2418   13.3                                             Дождь.   
2417   13.0                                    Ливень (ливни).   
2416   12.4                                    Ливень (ливни).   
2415   11.5                                    Ливень (ливни).   
2414   11.3                                    Ливень (ливни).   
2413   10.5                                    Ливень (ливни).   
2412   10.7                                             Дождь.   
2411   10.6                                             Дождь.   
2410    9.4                                             Дождь.   
2409    8.8                                             Дождь.   
2408    9.4                                             Дождь.   
2407   10.3                                             Дождь.   
2406   11.8                                             Дождь.   
2405   11.8                                             Дождь.   
2404   11.5                                             Дождь.   
2403    9.9                                             Дождь.   
2399   14.3                                    Ливень (ливни).   
2398   16.4                                    Лив

In [181]:
def preprocessing(data):
    processing_data = data
    for i in processing_data:
        if i[1] in {'Ливень (ливни).', 'Дождь.', 'Морось.', 'Гроза (грозы) с осадками или без них.'}:
            i[1] = 2
        elif i[1] in {'Снег и/или другие виды твердых осадков', 'Дождь со снегом или другими видами твердых осадков', 'Метель', 'Буря'}:
            i[1] = 3
        elif i[1] in {'Облака покрывали более половины неба в течение всего соответствующего периода.',
                      'Облака покрывали более половины неба в течение одной части соответствующего периода и половину или менее в течение другой части периода.',
                      'Туман или ледяной туман или сильная мгла.'}:
            i[1] = 1
        else:
            i[1] = 0
    return processing_data

In [182]:
def voiting(data):
    cond_0 = 0
    cond_1 = 0
    cond_2 = 0
    cond_3 = 0
    if len(data) != 8:
        for i in data:
            if i[1] == 0:
                cond_0 += 1
            if i[1] == 1:
                cond_1 += 1
            if i[1] == 2:
                cond_2 += 1
            if i[1] == 3:
                cond_3 += 1
    else:
        return data
    res = np.copy(data[0])
    res[1] = np.argmax([cond_0, cond_1, cond_2, cond_3])
    res[0] = np.mean(data.T[0])
    return res

In [183]:
def data_aggregate(data):
    new_data = np.array([])
    i = 0
    while i < data.shape[0]:
        _date = data[i][4]
        _status = data[i][7]
        processing = np.array([])
        processing = np.append(processing, np.copy(data[i]))
        if i+1 < data.shape[0]:
            while (data[i+1][4] == _date) and (data[i+1][7] == _status):
                processing = np.append(processing, data[i+1])
                processing = np.reshape(processing, (-1, len(data[i])))
                if i+2 < data.shape[0]:
                    i += 1
                else:
                    break
        result = voiting(processing)
        new_data = np.append(new_data, result)
        i += 1
    return np.reshape(new_data, (-1, len(data[i-1])))

$\begin{equation*}
T =
\begin{pmatrix}
su\rightarrow su & su\rightarrow c  & su\rightarrow r & su\rightarrow sn\\
c\rightarrow su & c\rightarrow c & c\rightarrow r & c\rightarrow sn\\
r\rightarrow su & r\rightarrow c & r\rightarrow r & r\rightarrow sn\\
sn\rightarrow su & sn\rightarrow c & sn\rightarrow r & sn\rightarrow sn
\end{pmatrix}
\end{equation*}$

In [184]:
def func_coef(data):
    #total = data.shape[0]
    rainy = 0
    sunny = 0
    snowy = 0
    cloudy = 0
    matrix = np.zeros((4, 4))
    i = 0
    while i < data.shape[0]-1:
        if data[i][1] == 2:
            rainy += 1
            matrix[2][data[i+1][1]] += 1 
        elif data[i][1] == 3:
            snowy += 1
            matrix[3][data[i+1][1]] += 1
        elif data[i][1] == 1:
            cloudy += 1
            matrix[1][data[i+1][1]] += 1
        else:
            sunny += 1
            matrix[0][data[i+1][1]] += 1
        i += 1 
    if sunny > 0:
        matrix[0] = matrix[0] / sunny
    if cloudy > 0:
        matrix[1] = matrix[1] / cloudy
    if rainy > 0:
        matrix[2] = matrix[2] / rainy
    if snowy > 0:
        matrix[3] = matrix[3] / snowy
    elif snowy == 0:
        matrix[3] = [0.25, 0.25, 0.25, 0.25]
    return matrix
    

In [185]:
t1 = preprocessing(table_np1)
t2 = preprocessing(table_np2)
t3 = preprocessing(table_np3)
t4 = preprocessing(table_np4)
t5 = preprocessing(table_np5)
t6 = preprocessing(table_np6)
t7 = preprocessing(table_np7)
t8 = preprocessing(table_np8)
t9 = preprocessing(table_np9)
t10 = preprocessing(table_np10)
t11 = preprocessing(table_np11)
t12 = preprocessing(table_np12)

data1 = data_aggregate(t1)
data2 = data_aggregate(t2)
data3 = data_aggregate(t3)
data4 = data_aggregate(t4)
data5 = data_aggregate(t5)
data6 = data_aggregate(t6)
data7 = data_aggregate(t7)
data8 = data_aggregate(t8)
data9 = data_aggregate(t9)
data10 = data_aggregate(t10)
data11 = data_aggregate(t11)
data12 = data_aggregate(t12)

In [186]:
print(data4)

[[3.85 1 '90  или более, но не 100%' ... 4 2010 0]
 [13.3 0 'Облаков нет.' ... 4 2010 1]
 [4.7 2 '90  или более, но не 100%' ... 4 2010 0]
 ...
 [6.2 2 '100%.' ... 4 2020 1]
 [4.1000000000000005 2 '90  или более, но не 100%' ... 4 2020 0]
 [5.2 2 '70 – 80%.' ... 4 2020 0]]


In [187]:
M1 = func_coef(data1)
M2 = func_coef(data2)
M3 = func_coef(data3)
M4 = func_coef(data4)
M5 = func_coef(data5)
M6 = func_coef(data6)
M7 = func_coef(data7)
M8 = func_coef(data8)
M9 = func_coef(data9)
M10 = func_coef(data10)
M11 = func_coef(data11)
M12 = func_coef(data12)

In [171]:
M = []
M.append(M1)
M.append(M2)
M.append(M3)
M.append(M4)
M.append(M5)
M.append(M6)
M.append(M7)
M.append(M8)
M.append(M9)
M.append(M10)
M.append(M11)
M.append(M12)

In [198]:
M[4]

array([[0.79234973, 0.00546448, 0.20218579, 0.        ],
       [0.03448276, 0.31034483, 0.65517241, 0.        ],
       [0.06595365, 0.03386809, 0.89304813, 0.00713012],
       [0.        , 0.        , 0.8       , 0.2       ]])

In [199]:
M4

array([[0.61616162, 0.05050505, 0.3030303 , 0.03030303],
       [0.2       , 0.17142857, 0.6       , 0.02857143],
       [0.13242009, 0.09589041, 0.68949772, 0.08219178],
       [0.08      , 0.08      , 0.72      , 0.12      ]])

In [123]:
np.sum(M12, axis=1)

array([1., 1., 1., 1.])

In [91]:
#(ясно, облачно, дождь, снег)

In [104]:
np.array([1, 0, 0, 0]) @ M7

array([0.74, 0.04, 0.22, 0.  ])

# Temperature

In [137]:
def temp_comp(data):
    result = np.array([])
    i = 0
    while i < data.shape[0]-1:
        if data[i+1][0] - data[i][0] < -5:
            result = np.append(result, 0)
        elif (data[i+1][0] - data[i][0] >= -5) and (data[i+1][0] - data[i][0] < -2):
            result = np.append(result, 1)
        elif (data[i+1][0] - data[i][0] >= -2) and (data[i+1][0] - data[i][0] <= 2):
            result = np.append(result, 2)
        elif (data[i+1][0] - data[i][0] > 2) and (data[i+1][0] - data[i][0] <= 5):
            result = np.append(result, 3)
        else:
            result = np.append(result, 4)
        i += 1
    return result

In [138]:
diff1 = temp_comp(data1)
diff2 = temp_comp(data2)
diff3 = temp_comp(data3)
diff4 = temp_comp(data4)
diff5 = temp_comp(data5)
diff6 = temp_comp(data6)
diff7 = temp_comp(data7)
diff8 = temp_comp(data8)
diff9 = temp_comp(data9)
diff10 = temp_comp(data10)
diff11 = temp_comp(data11)
diff12 = temp_comp(data12)

In [139]:
def temp_matrix(data):
    l5 = 0
    l2 = 0
    b = 0
    m2 = 0
    m5 = 0
    matrix = np.zeros((5, 5))
    i = 0
    while i < data.shape[0]-1:
        if data[i] == 0:
            l5 += 1
            matrix[0][int(data[i+1])] += 1
        elif data[i] == 1:
            l2 += 1
            matrix[1][int(data[i+1])] += 1
        elif data[i] == 2:
            b += 1
            matrix[2][int(data[i+1])] += 1
        elif data[i] == 3:
            m2 += 1
            matrix[3][int(data[i+1])] += 1
        else:
            m5 += 1
            matrix[4][int(data[i+1])] += 1
        i += 1
    if l5 > 0:
        matrix[0] = matrix[0] / l5
    elif l5 == 0:
        matrix[0] = [0.333, 0.333, 0.333, 0.333]
    if l2 > 0:
        matrix[1] = matrix[1] / l2
    elif l2 == 0:
        matrix[1] = [0.333, 0.333, 0.333, 0.333]
    if b > 0:
        matrix[2] = matrix[2] / b
    elif b == 0:
        matrix[2] = [0.333, 0.333, 0.333, 0.333]
    if m2 > 0:
        matrix[3] = matrix[3] / m2
    elif b == 0:
        matrix[3] = [0.333, 0.333, 0.333, 0.333]
    if m5 > 0:
        matrix[4] = matrix[4] / m5
    elif m5 == 0:
        matrix[4] = [0.333, 0.333, 0.333, 0.333]
    return matrix

In [140]:
T1 = temp_matrix(diff1)
T2 = temp_matrix(diff2)
T3 = temp_matrix(diff3)
T4 = temp_matrix(diff4)
T5 = temp_matrix(diff5)
T6 = temp_matrix(diff6)
T7 = temp_matrix(diff7)
T8 = temp_matrix(diff8)
T9 = temp_matrix(diff9)
T10 = temp_matrix(diff10)
T11 = temp_matrix(diff11)
T12 = temp_matrix(diff12)

In [141]:
np.array([0, 0, 1, 0, 0]) @ T5

array([0.07079646, 0.21238938, 0.40707965, 0.18584071, 0.12389381])

In [169]:
T1

array([[0.15      , 0.1       , 0.35      , 0.2       , 0.2       ],
       [0.04819277, 0.10843373, 0.53012048, 0.19277108, 0.12048193],
       [0.02531646, 0.17721519, 0.67721519, 0.10126582, 0.01898734],
       [0.02985075, 0.19402985, 0.59701493, 0.14925373, 0.02985075],
       [0.125     , 0.125     , 0.45833333, 0.20833333, 0.08333333]])