In [2]:
import numpy as np
import pandas as pd
import time
import datetime

In [3]:
data = pd.read_csv('worldweatheronline.com/result_data.csv')

In [4]:
table0 = data[['date', 'time', 'tempC', 'weatherDesc']]

In [5]:
table0.head()

date  time  tempC   weatherDesc
0  2009-04-01     0      0           Fog
1  2009-04-01  1200      2           Fog
2  2009-04-02     0      0      Overcast
3  2009-04-02  1200      1      Overcast
4  2009-04-03     0     -2  Freezing fog

In [39]:
table0['day'] = [time.strptime(n, "%Y-%m-%d").tm_mday for n in table0['date']]
table0['month'] = [time.strptime(n, "%Y-%m-%d").tm_mon for n in table0['date']]
table0['year'] = [time.strptime(n, "%Y-%m-%d").tm_year for n in table0['date']]
table0['status'] = [0 if n == 0 else 1 for n in table0['time']]
table0.drop(['date'], axis='columns', inplace=True)

/home/dmitry/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/home/dmitry/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/home/dmitry/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the docum

In [40]:
table1 = table0.loc[(table0['month'] == 1)]
table2 = table0.loc[(table0['month'] == 2)]
table3 = table0.loc[(table0['month'] == 3)]
table4 = table0.loc[(table0['month'] == 4)]
table5 = table0.loc[(table0['month'] == 5)]
table6 = table0.loc[(table0['month'] == 6)]
table7 = table0.loc[(table0['month'] == 7)]
table8 = table0.loc[(table0['month'] == 8)]
table9 = table0.loc[(table0['month'] == 9)]
table10 = table0.loc[(table0['month'] == 10)]
table11 = table0.loc[(table0['month'] == 11)]
table12 = table0.loc[(table0['month'] == 12)]
table_np1 = table1.values
table_np2 = table2.values
table_np3 = table3.values
table_np4 = table4.values
table_np5 = table5.values
table_np6 = table6.values
table_np7 = table7.values
table_np8 = table8.values
table_np9 = table9.values
table_np10 = table10.values
table_np11 = table11.values
table_np12 = table12.values

In [53]:
table1.head()

time  tempC   weatherDesc  day  month  year  status
550     0    -10  Freezing fog    1      1  2010       0
551  1200     -9          Mist    1      1  2010       1
552     0    -13  Freezing fog    2      1  2010       0
553  1200    -10  Freezing fog    2      1  2010       1
554     0    -15      Overcast    3      1  2010       0

In [41]:
def preprocessing(data):
    processing_data = data
    for i in processing_data:
        if i[2] in {'Thundery outbreaks possible','Moderate rain',
                    'Light drizzle','Light freezing rain','Moderate or heavy rain shower',
                    'Patchy rain possible','Light rain shower','Patchy light drizzle',
                    'Light rain','Moderate or heavy rain with thunder',
                    'Moderate rain at times', 'Heavy rain','Patchy light rain',
                    'Patchy light rain with thunder'}:
            i[2] = 2
        elif i[2] in {'Light snow','Patchy moderate snow','Heavy freezing drizzle',
                      'Moderate snow', 'Heavy snow', 'Light snow showers',
                      'Moderate or heavy sleet', 'Moderate or heavy snow showers',
                      'Light sleet','Light sleet showers','Patchy snow possible',
                      'Blizzard','Patchy heavy snow','Patchy light snow'}:
            i[2] = 3
        elif i[2] in {'Fog','Overcast','Freezing fog','Mist','Partly cloudy'}:
            i[2] = 1
        else:
            i[2] = 0
    return processing_data

In [42]:
def func_coef(data):
    #total = data.shape[0]
    rainy = 0
    sunny = 0
    snowy = 0
    cloudy = 0
    matrix = np.zeros((4, 4))
    i = 0
    while i < data.shape[0]-1:
        if data[i][2] == 2:
            rainy += 1
            matrix[2][data[i+1][2]] += 1 
        elif data[i][2] == 3:
            snowy += 1
            matrix[3][data[i+1][2]] += 1
        elif data[i][2] == 1:
            cloudy += 1
            matrix[1][data[i+1][2]] += 1
        else:
            sunny += 1
            matrix[0][data[i+1][2]] += 1
        i += 1 
    if sunny > 0:
        matrix[0] = matrix[0] / sunny
    elif sunny == 0:
        matrix[0] = [0.25, 0.25, 0.25, 0.25]
    if cloudy > 0:
        matrix[1] = matrix[1] / cloudy
    elif cloudy == 0:
        matrix[1] = [0.25, 0.25, 0.25, 0.25]
    if rainy > 0:
        matrix[2] = matrix[2] / rainy
    elif rainy == 0:
        matrix[2] = [0.25, 0.25, 0.25, 0.25]
    if snowy > 0:
        matrix[3] = matrix[3] / snowy
    elif snowy == 0:
        matrix[3] = [0.25, 0.25, 0.25, 0.25]
    return matrix

In [43]:
t1 = preprocessing(table_np1)
t2 = preprocessing(table_np2)
t3 = preprocessing(table_np3)
t4 = preprocessing(table_np4)
t5 = preprocessing(table_np5)
t6 = preprocessing(table_np6)
t7 = preprocessing(table_np7)
t8 = preprocessing(table_np8)
t9 = preprocessing(table_np9)
t10 = preprocessing(table_np10)
t11 = preprocessing(table_np11)
t12 = preprocessing(table_np12)

In [96]:
M1 = func_coef(t1)
M2 = func_coef(t2)
M3 = func_coef(t3)
M4 = func_coef(t4)
M5 = func_coef(t5)
M6 = func_coef(t6)
M7 = func_coef(t7)
M8 = func_coef(t8)
M9 = func_coef(t9)
M10 = func_coef(t10)
M11 = func_coef(t11)
M12 = func_coef(t12)

In [125]:
M1

array([[0.30769231, 0.66153846, 0.        , 0.03076923],
       [0.07792208, 0.86085343, 0.01298701, 0.04823748],
       [0.        , 0.45454545, 0.27272727, 0.27272727],
       [0.04545455, 0.39393939, 0.01515152, 0.54545455]])

In [122]:
M = np.array([])
M = np.append(M, M1)
M = np.append(M, M2)
M = np.append(M, M3)
M = np.append(M, M4)
M = np.append(M, M5)
M = np.append(M, M6)
M = np.append(M, M7)
M = np.append(M, M8)
M = np.append(M, M9)
M = np.append(M, M10)
M = np.append(M, M11)
M = np.append(M, M12)

In [127]:
M = np.reshape(M, (12,4,4))

In [142]:
np.save('matrices/matrix1', M)  

In [143]:
my_matrix = np.load(open("matrices/matrix1.npy","rb"))

In [144]:
my_matrix

array([[[0.30769231, 0.66153846, 0.        , 0.03076923],
        [0.07792208, 0.86085343, 0.01298701, 0.04823748],
        [0.        , 0.45454545, 0.27272727, 0.27272727],
        [0.04545455, 0.39393939, 0.01515152, 0.54545455]],

       [[0.34545455, 0.6       , 0.        , 0.05454545],
        [0.06361829, 0.89065606, 0.00795229, 0.03777336],
        [0.        , 0.5       , 0.25      , 0.25      ],
        [0.07272727, 0.30909091, 0.03636364, 0.58181818]],

       [[0.28723404, 0.69148936, 0.        , 0.0212766 ],
        [0.11494253, 0.81226054, 0.02873563, 0.0440613 ],
        [0.08695652, 0.47826087, 0.2173913 , 0.2173913 ],
        [0.11904762, 0.5       , 0.07142857, 0.30952381]],

       [[0.52232143, 0.4375    , 0.04017857, 0.        ],
        [0.24582339, 0.69689737, 0.04295943, 0.01431981],
        [0.075     , 0.625     , 0.25      , 0.05      ],
        [0.09090909, 0.36363636, 0.27272727, 0.27272727]],

       [[0.59930314, 0.3554007 , 0.04529617, 0.        ],
      

$\begin{equation*}
T =
\begin{pmatrix}
su\rightarrow su & su\rightarrow c  & su\rightarrow r & su\rightarrow sn\\
c\rightarrow su & c\rightarrow c & c\rightarrow r & c\rightarrow sn\\
r\rightarrow su & r\rightarrow c & r\rightarrow r & r\rightarrow sn\\
sn\rightarrow su & sn\rightarrow c & sn\rightarrow r & sn\rightarrow sn
\end{pmatrix}
\end{equation*}$

In [67]:
def temp_comp(data):
    result = np.array([])
    i = 0
    while i < data.shape[0]-1:
        if data[i+1][1] - data[i][1] < -5:
            result = np.append(result, 0)
        elif (data[i+1][1] - data[i][1] >= -5) and (data[i+1][1] - data[i][1] < -2):
            result = np.append(result, 1)
        elif (data[i+1][1] - data[i][1] >= -2) and (data[i+1][1] - data[i][1] <= 2):
            result = np.append(result, 2)
        elif (data[i+1][1] - data[i][1] > 2) and (data[i+1][1] - data[i][1] <= 5):
            result = np.append(result, 3)
        else:
            result = np.append(result, 4)
        i += 1
    return result

In [68]:
diff1 = temp_comp(t1)
diff2 = temp_comp(t2)
diff3 = temp_comp(t3)
diff4 = temp_comp(t4)
diff5 = temp_comp(t5)
diff6 = temp_comp(t6)
diff7 = temp_comp(t7)
diff8 = temp_comp(t8)
diff9 = temp_comp(t9)
diff10 = temp_comp(t10)
diff11 = temp_comp(t11)
diff12 = temp_comp(t12)

In [72]:
def temp_matrix(data):
    l5 = 0
    l2 = 0
    b = 0
    m2 = 0
    m5 = 0
    matrix = np.zeros((5, 5))
    i = 0
    while i < data.shape[0]-1:
        if data[i] == 0:
            l5 += 1
            matrix[0][int(data[i+1])] += 1
        elif data[i] == 1:
            l2 += 1
            matrix[1][int(data[i+1])] += 1
        elif data[i] == 2:
            b += 1
            matrix[2][int(data[i+1])] += 1
        elif data[i] == 3:
            m2 += 1
            matrix[3][int(data[i+1])] += 1
        else:
            m5 += 1
            matrix[4][int(data[i+1])] += 1
        i += 1
    if l5 > 0:
        matrix[0] = matrix[0] / l5
    elif l5 == 0:
        matrix[0] = [0.2, 0.2, 0.2, 0.2, 0.2]
    if l2 > 0:
        matrix[1] = matrix[1] / l2
    elif l2 == 0:
        matrix[1] = [0.2, 0.2, 0.2, 0.2, 0.2]
    if b > 0:
        matrix[2] = matrix[2] / b
    elif b == 0:
        matrix[2] = [0.2, 0.2, 0.2, 0.2, 0.2]
    if m2 > 0:
        matrix[3] = matrix[3] / m2
    elif b == 0:
        matrix[3] = [0.2, 0.2, 0.2, 0.2, 0.2]
    if m5 > 0:
        matrix[4] = matrix[4] / m5
    elif m5 == 0:
        matrix[4] = [0.2, 0.2, 0.2, 0.2, 0.2]
    return matrix

In [73]:
T1 = temp_matrix(diff1)
T2 = temp_matrix(diff2)
T3 = temp_matrix(diff3)
T4 = temp_matrix(diff4)
T5 = temp_matrix(diff5)
T6 = temp_matrix(diff6)
T7 = temp_matrix(diff7)
T8 = temp_matrix(diff8)
T9 = temp_matrix(diff9)
T10 = temp_matrix(diff10)
T11 = temp_matrix(diff11)
T12 = temp_matrix(diff12)

In [74]:
T1

array([[0.01785714, 0.05357143, 0.26785714, 0.25      , 0.41071429],
       [0.056     , 0.064     , 0.36      , 0.312     , 0.208     ],
       [0.06012658, 0.17088608, 0.5664557 , 0.17088608, 0.03164557],
       [0.13675214, 0.35042735, 0.42735043, 0.05982906, 0.02564103],
       [0.1969697 , 0.28787879, 0.39393939, 0.06060606, 0.06060606]])

In [145]:
T = np.array([])
T = np.append(T, T1)
T = np.append(T, T2)
T = np.append(T, T3)
T = np.append(T, T4)
T = np.append(T, T5)
T = np.append(T, T6)
T = np.append(T, T7)
T = np.append(T, T8)
T = np.append(T, T9)
T = np.append(T, T10)
T = np.append(T, T11)
T = np.append(T, T12)

In [148]:
T = np.reshape(T, (12,5,5))

In [149]:
np.save('matrices/matrix2', T)  

In [151]:
my_matrix2 = np.load(open("matrices/matrix2.npy","rb"))

In [152]:
my_matrix2

array([[[0.01785714, 0.05357143, 0.26785714, 0.25      , 0.41071429],
        [0.056     , 0.064     , 0.36      , 0.312     , 0.208     ],
        [0.06012658, 0.17088608, 0.5664557 , 0.17088608, 0.03164557],
        [0.13675214, 0.35042735, 0.42735043, 0.05982906, 0.02564103],
        [0.1969697 , 0.28787879, 0.39393939, 0.06060606, 0.06060606]],

       [[0.        , 0.01123596, 0.06741573, 0.21348315, 0.70786517],
        [0.        , 0.04166667, 0.36458333, 0.4375    , 0.15625   ],
        [0.12301587, 0.13492063, 0.59920635, 0.11904762, 0.02380952],
        [0.20833333, 0.38541667, 0.375     , 0.02083333, 0.01041667],
        [0.43678161, 0.22988506, 0.28735632, 0.03448276, 0.01149425]],

       [[0.        , 0.01785714, 0.05357143, 0.24107143, 0.6875    ],
        [0.00694444, 0.00694444, 0.21527778, 0.53472222, 0.23611111],
        [0.12426036, 0.17159763, 0.47928994, 0.18343195, 0.04142012],
        [0.27007299, 0.46715328, 0.25547445, 0.00729927, 0.        ],
        [0.44915